config/routes.rb
Rails.application.routes.draw do
  
  get    "admin"  => "access#index"
  get    "login"  => "access#new"
  post   "login"  => "access#create"
  delete    "logout" => "access#logout"
 

  root "subjects#index"
  get "demo/index"
  get "demo/hello"

  resources :subjects
  resources :pages
  resources :sections
  

end

app/models/section.rb
class Section < ActiveRecord::Base
 
  
  belongs_to :page
  has_many :section_edits
  has_many :editors, :through => :section_edits, :class_name => "AdminUser"
  
  CONTENT_TYPES = ["Text", "HTML"]
  validates :name, presence: true, length: { maximum: 255 }
  validates :content, presence: true 
  validaes :contenT_type, inclusion: { in: CONTENT_TYPES }, 
                            message: "must  be one of #{CONTENT_TYPES.join(", ")} "
  
  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("sections.position ASC") }
  scope :newest_first, lambda { order("sections.created_at DESC")}
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  
  layout 'admin'
  
  before_action :confirm_logged_in
  
  def index 
    @sections = Section.all
  end 
  
  def show
    @section = Section.find(params[:id])
  end 
  
  def new 
    @section = Section.new 
  end 
  
  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:notice] = "Section Created Successfully"
      redirect_to sections_path
    else 
      flash.now[:error] = "Section error"
      render :new 
    end 
  end 
  
  def edit 
    @section = Section.find(params[:id])
  end 
  
  def update 
    @section = Section.find(params[:id])
    if @section.update(section_params)
      flash[:notice] = "Section Updated Successfully"
      redirect_to sections_path(@section)
    else
      flash.now[:error] = "Error. Please fix."
      render :edit 
    end 
  end 
  
  def delete
    @section = Section.find(params[:id])
  end 
  
  def destroy
    @section = Section.find(params[:id])
    @section.destroy 
    flash[:notice] = "Section #{@section.name} has been deleted successfully"
    redirect_to sections_path 
  end 
  
  private 
  
  def section_params
    params.require(:section).permit(:page_id, :name, :position, :visible, :content_type, :content, :created_at, :updated_at)
  end 
  
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= error_messages_for(@section) %>

<table summary="Section form fields">
      <tr>
        <th><%= f.label :page_id, "Page ID" %></th>
        <td><%= f.text_field(:page_id) %></td>
      </tr>
      <tr>
        <th> <%= f.label :name %> </th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th> <%= f.label :position %></th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th><%= f.label :visible %></th>
        <td><%= f.check_box(:visible) %></td>
      </tr>
      <tr>
        <th><%= f.label :content_type, "Content Type" %></th>
        <td>
          <%= f.radio_button(:content_type, "Text") %> Text
          <%= f.radio_button(:content_type, "HTML") %> HTML
        </td>
      </tr>
      <tr>
        <th><%= f.label :content %></th>
        <td><%= f.text_area(:content, size: "40x10") %></td>
      </tr>
    </table>

app/views/sections/edit.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="sections edit">
  <h2>Update Section</h2>

  <%= form_for @section, url: section_path do |f| %>
   <%= render partial: "form", locals: {f: f} %>
    <div class="form-buttons">
      <%= submit_tag("Update Section") %>
    </div>

  <% end %>
</div>

app/views/sections/index.html.erb
<div class="sections index">
  <h2>Sections</h2>

  <%= link_to("Add New Section", {:action => 'new'}, :class => 'action new') %>

  <table class="listing" summary="Section list">
    <tr class="header">
      <th>&nbsp;</th>
      <th>Page ID</th>
      <th>Section</th>
      <th>Content Type</th>
      <th>Visible</th>
      <th>Actions</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      <td><%= section.position %></td>
      <td><%= section.page_id %></td>
      <td><%= section.name %></td>
      <td><%= section.content_type %></td>
      <td class="center"><%= section.visible ? 'Yes' : 'No' %></td>
      <td class="actions">
        <%= link_to("Show", section_path(section), :class => 'action show') %>
        <%= link_to("Edit", edit_section_path(section), :class => 'action edit') %>
        <%= link_to("Delete", section_path(section), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/sections/new.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="sections new">
  <h2>Create Section</h2>

  <%= form_for @section, url: sections_path do |f| %>
    <%= render partial: "form", locals: {f: f} %>
    <div class="form-buttons">
      <%= submit_tag("Create Section") %>
    </div>

  <% end %>
</div>

app/views/sections/show.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>
<div class="sections show">
  <h2>Show Section</h2>

  <table summary="Section detail view">
    <tr>
      <th>Page ID</th>
      <td><%= @section.page_id %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Content Type</th>
      <td><%= @section.content_type %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= @section.content %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>

</div>