config/routes.rb
Rails.application.routes.draw do
  
  get    "admin"  => "access#index"
  get    "login"  => "access#new"
  post   "login"  => "access#create"
  delete    "logout" => "access#logout"
 

  root "subjects#index"
  get "demo/index"
  get "demo/hello"

  resources :subjects
  resources :pages
  resources :sections
  

end

app/views/pages/_form.html.erb
  <%= error_messages_for(@page) %>
  <table summary="Page form fields">
      <tr>
        <th><%= f.label :subject_id, "Subject" %></th>
        <td><%= f.select(:subject_id, @subjects.map {|s| [s.name, s.id] } ) %></td>
      </tr>
      <tr>
        <th><%= f.label :name %></th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th><%= f.label :permalink %></th>
        <td><%= f.text_field(:permalink) %></td>
      </tr>
      <tr>
        <th><%= f.label :position %></th>
        <td><%= f.select(:position, 1..@page_count) %></td>
      </tr>
      <tr>
        <th><%= f.label :visible %> </th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
    </table>

app/views/pages/delete.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Page</h2>

  <%= form_for @page, :url pages_path do |f| %>

    <p>Are you sure you want to permanently delete this page?</p>

    <p class="reference-name"><%= @page.name %></p>

    <div class="form-buttons">
      <%= f.submit ("Delete Page") %>
    </div>

  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="pages edit">
  <h2>Edit Page</h2>

  <%= form_for @page, url: page_path do |f| %>
    <%= render partial: "form", locals: {f: f} %>
    <div class="form-buttons">
      <%= submit_tag("Update Page") %>
    </div>

  <% end %>
</div>

app/views/pages/index.html.erb
<div class="pages index">
  <h2>Pages</h2>

  <%= link_to("Add New Page", new_page_path, :class => 'action new') %>

  <table class="listing" summary="Page list">
    <tr class="header">
      <th>&nbsp;</th>
      <th>Subject</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %></td>
      <td><%= page.subject.name if page.subject %></td>
      <td><%= page.name %></td>
      <td><%= page.permalink %></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="center"><%= page.sections.size ? 'Yes' : 'No' %></td>
      <td class="actions">
        <%= link_to("Show",    page_path(page),      :class => 'action show') %>
        <%= link_to("Edit",    edit_page_path(page), :class => 'action edit') %>
        <%= link_to("Destroy", page_path(page),     method: :delete ) %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="pages new">
  <h2>Create Pages</h2>

 
  <%= form_for @page, url: pages_path do |f| %>
    <%= render partial: "pages/form", locals: {f: f} %>
    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>

  <% end %>
</div>

app/views/pages/show.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="pages show">
  <h2>Show Page</h2>

  <table summary="Page detail view">
    <tr>
      <th>Subject ID</th>
      <td><%= @page.subject_id %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>

</div>