config/routes.rb
Rails.application.routes.draw do
  
  get    "admin"  => "access#index"
  get    "login"  => "access#new"
  post   "login"  => "access#create"
  delete    "logout" => "access#logout"
 

  root "subjects#index"
  get "demo/index"
  get "demo/hello"

  resources :subjects
  resources :pages
  resources :sections
  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :pages
  validates :name, presence: true, length: { maximum: 255 }
  
  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("subjects.position ASC") }
  scope :newest_first, lambda { order("subjects.created_at DESC")}
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  layout 'admin'
  
  before_action :confirm_logged_in
  
  
  def index 
    @subjects = Subject.all 
  end 
  
  def show 
    @subject = Subject.find(params[:id])
  end 
  
  def new 
    @subject = Subject.new 
    @subject_count = Subject.count + 1
  end 
  
  def create 
    @subject = Subject.new(subjects_param)
    if @subject.save 
      flash[:notice] = "Subject Created Succesfully"
      redirect_to subjects_path
    else 
      flash.now[:error] = "Error. Please try again"
      @subject_count = Subject.count + 1
      render "new"
    end 
  end 
  
  def edit 
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count 
  end 
  
  def update 
    @subject = Subject.find(params[:id])
    if @subject.update(subjects_param)
      flash[:notice] = "Subject Updated Succesfully"
      redirect_to subject_path(@subject)
    else
      @subject_count = Subject.count 
      render :edit 
    end 
  end 
  
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy 
    flash[:notice] = "Subject #{@subject.name} Destroyed Succesfully"
    redirect_to subjects_path 
  end 
  
  private 
  
  def subjects_param 
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end 
end

app/helpers/subjects_helper.rb
module SubjectsHelper
 
end

app/views/subjects/_form.html.erb
<!--- Stuff above -->
<%= error_messages_for(@subject) %>
  <table summary="Subject form fields">
    <tr>
      <th><%= f.label :name %> </th>
      <td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
      <th><%= f.label  :position %> </th>
      <td><%= f.select :position, 1..@subject_count %></td>
    </tr>
    <tr>
      <th><%= f.label :visible %> </th>
      <td><%= f.check_box(:visible) %></td>
    </tr>
      <tr>
      <th><%= f.label :created_at %> </th>
      <td><%= f.datetime_select(:created_at, ) %></td>
    </tr>
  </table>
  <!--- Submit button --->

app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>
  <%= form_for @subject, url: subject_path do |f| %>
    <%= render(:partial => "form", :locals => {:f => f}) %> <!--- form table  --->
   <div class="form-buttons">
    <%= f.submit ("Update Subject") %>
   </div>
  <% end %>
</div>

app/views/subjects/index.html.erb
<% @page_title = "Subjects" %>
<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <div> <%= pluralize(@subjects.size, 'subject') %> </div>
  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>&nbsp;</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= status_tag(subject.visible) %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
       
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to 'Destroy', subject_path(subject),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>
  <%= form_for @subject, url: subjects_path do |f| %>
    <%= render(partial: "form", locals: {f: f}) %>
    <div class="form-buttons">
      <%= f.submit ("Create Subject") %>
    </div>
    
  <% end %>
</div>

app/views/subjects/show.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>